config/routes.rb
UpYourSleeve::Application.routes.draw do

root  'pages#home'

match '/about',   to: 'pages#about',   via: 'get'
match '/projects',    to: 'pages#projects',    via: 'get'
match '/contact', to: 'pages#contact', via: 'get'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper :all
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_filter :prepare_for_mobile

	private

	def mobile_device?
  		if 	session[:mobile_param]
  			session[:mobile_param] == "1"
  		else
  			request.user_agent =~ /Mobile|webOS/
  		end
  	end
  	
  	helper_method :mobile_device?

  	def prepare_for_mobile
  		session[:mobile_param] = params[:mobile] if params[:mobile]
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Up your sleeve"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.facebook.com/rickard.nilsson/">Rickard Nilsson</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact",   contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
        	<%= link_to "up your sleeve", root_path, id: "logo" %>

          	<nav>
	            <ul class="nav pull-right">
	            	<li><%= link_to "Home", root_path %></li>
                    <li><a href="http://ricknil.mooo.com"> WeWiki </a> </li>

                    <!-- <li>
                        <% if mobile_device? %>
                            <%= link_to "Normal Site", :mobile => 0 %>
                        <% else %>
                            <%= link_to "Mobile Site", :mobile => 1 %>
                        <% end %>
                    </li> -->

                    <li><%= link_to "Projects", projects_path %></li>

	            </ul>
          	</nav>

        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> <%= full_title(yield(:title)) %> </title>
		
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		
		<!-- For mobile devices -->
		<%= stylesheet_link_tag "mobile" if mobile_device? %>
		
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>

		<%= render 'layouts/shim' %>
	
	</head>

	<body>

		<%= render 'layouts/header' %>

	    <div class="container">
			<%= yield %>
			
			<%= render 'layouts/footer' %>

		</div>

	</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>

<div class="center hero-unit">
	<h1> God Jul <a href="http://www.facebook.com/rickard.nilsson/">Rickard</a>! </h1>

	<p>Detta är din alldeles egen hemsida som du får fylla med vad du vill, alltefter behov! (enda kravet är att det är en Rails-app..) <br>
	Vill du så hjälper jag till med att lägga till det du vill så håller jag det jag lärt mig vid liv :) </p> 

	<p>Kanske vill du och Robin/Martin använda sidan till gemensamma projekt? Kanske blir det ett ställe att dela med dig av vad Knodden pysslar med? Det är du som brukar ha alla idéer... :P </p>

	<p>Koden ligger i ett repository på gitgub: <a href="https://github.com/attback/up-your-sleeve">github.com/attback/up-your-sleeve</a>, fritt fram att klona. <br>
	Sidan är sedan deployad på Heroku och du kommer åt den på <a href="http://www.up-your-sleeve.herokuapp.com">up-your-sleeve.herokuapp.com</a> men vid det här laget vet du väl ett nördigare sätt att komma åt den?! <br>
	Jag kommer bjuda in dig som Collaborator till den appen inom kort så att du också kan pusha upp ändringar.</p>

	<p>Puss på dej!</p>

</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="center hero-unit">
	<h1>Contact</h1>
	<p>
	  Contact <a href="http://www.facebook.com/attback">Josefin</a> for help or update requests of the site!
	</p>
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit" >
	<h1 id="home_header"> Happy Holidays </h1>
		
	<p>Mot årets jul det lackade <br>
	Jag ivrigt satt och hackade </p>

	<p>För varje bra manschettknapp <br>
	Ju länkar till en web-app </p>

	<p>Använd till ett nytt projekt <br>
	Till wiki, blogg och lek med släkt? </p>
	
	<p>Och när Knoddis sover bäst <br>
	Då gör jag din change request </p>

	<p>Nästan vad du än begär <br>
	Det, min fina Rickard kär </p>
	
	<p>Ska jag så försöka koda <br>
	På min lilla datorlåda </p>

	<p>Det kan blir mitt tidsfördriv <br>
	För att hålla sånt vid liv </p>

	<p>Som jag lärt på detta år<br>
	Så att jag mer jobb sen får</p>

	<p>Annars ska jag assistera <br>
	Om du vill dig lära mera </p>
	
	<p>Om rälsar och rubiner <br>
	Om script och subrutiner </p>

	<p>Med länk direkt till skärmen <br>
	Ett äss du har på ärmen </p>
	
	<p>En God Jul önskas så igen<br>
	Till dig, min älskade och vän!</p>

</div>

<%= audio_tag "sleighbells.wav", :autoplay => true %>

app/views/pages/projects.html.erb
<% provide(:title, 'Projects') %>

<div class="center hero-unit">
	<h1>Projects</h1>
	<p>Kanske kan du ha gemensamma projekt här, du har ju en projektavdelning på wewikin redan för allt ditt egna :) </p>
	<br>
	<ul id="projectlist">
	  <li>RFID-sändare</li>
	  <li>Vad mer du nu håller på med..</li>
	  <li>Nya idéer</li>
	</ul>
</div>